<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-ios</TargetFramework>
    <ImplicitUsings>true</ImplicitUsings>
    <IsBindingProject>true</IsBindingProject>
  </PropertyGroup>
  <ItemGroup>
    <ObjcBindingApiDefinition Include="ApiDefinition.cs" />
  </ItemGroup>
  <ItemGroup>
    <ObjcBindingCoreSource Include="Structs.cs" />
  </ItemGroup>
  <ItemGroup>
    <NativeReference Include="..\..\externals\MaterialComponents.xcframework">
      <Kind>Framework</Kind>
      <Frameworks>CoreGraphics QuartzCore</Frameworks>
      <ForceLoad>True</ForceLoad>
      <LinkerFlags>-ObjC</LinkerFlags>
    </NativeReference>
    <NativeReference Include="..\..\externals\MDFInternationalization.xcframework">
      <Kind>Framework</Kind>
      <ForceLoad>True</ForceLoad>
    </NativeReference>
    <NativeReference Include="..\..\externals\MDFTextAccessibility.xcframework">
      <Kind>Framework</Kind>
      <ForceLoad>True</ForceLoad>
    </NativeReference>
    <NativeReference Include="..\..\externals\MotionAnimator.xcframework">
      <Kind>Framework</Kind>
      <ForceLoad>True</ForceLoad>
    </NativeReference>
    <NativeReference Include="..\..\externals\MotionInterchange.xcframework">
      <Kind>Framework</Kind>
      <ForceLoad>True</ForceLoad>
    </NativeReference>
    <NativeReference Include="..\..\externals\MotionTransitioning.xcframework">
      <Kind>Framework</Kind>
      <ForceLoad>True</ForceLoad>
    </NativeReference>
  </ItemGroup>
</Project>